# yaml-language-server: $schema=https://render.com/schema/render.yaml.json

services:
  - type: web
    name: er-system-web-client
    runtime: static
    rootDir: Web/Frontend/ersystem-web-client
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: off
    envVars:
      - key: NODE_VERSION
        value: 24.18.0
      - key: SKIP_INSTALL_DEPS
        value: "true"
      - key: VITE_API_BASE_URL
        value: https://192.168.4.206:5080
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
